Back to old error reporting

diff --git a/.github/workflows/validate-structure.yml b/.github/workflows/validate-structure.yml
--- a/.github/workflows/validate-structure.yml
+++ b/.github/workflows/validate-structure.yml
@@ -19,5 +19,6 @@ jobs:
           num_zonefiles="$(ls  ${{ env.ZONE_FILE }} | wc -l)"
           if [ "$num_zonefiles" != 1 ];
           then
-            echo "::setFailed::Incorrect number of Zone files. Expected 1, got $num_zonefiles"
+            echo "::error::Incorrect number of Zone files. Expected 1, got $num_zonefiles"
+            exit 1
           fi
